# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Shopinvader
org_slug: shopinvader
rebel_module_groups: []
repo_description: Easy, reproductible and reliable imports and exports
repo_name: Pattern Import Export
repo_slug: pattern-import-export
repo_website: https://github.com/Shopinvader/pattern-import-export
use_pyproject_toml: false
use_ruff: true

